import { readFileSync, realpathSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { formatInstallationLine, installationFields, InstallationError, namesResolvedInstallation, requestedInstallation, requireResolvedInstallation, resolveInstallation, type Installation, type InstallationConfig } from '@helmo/core';
import { runningLine, runningRef } from './build.js';
const config: InstallationConfig = { homeKey: 'HELMO_HOME', dbKey: 'HELMO_DB', defaultHome: '.helmo', defaultDb: 'helmo.db', derivedPrefix: 'dev.helmo', homePattern: /^\.helmo([-_.]|$)/, stripPattern: /^\.?helmo(?=[-_.]|$)/, release: (env) => selectedRelease('helmo', env) };
export { InstallationError, requestedInstallation }; export type { Installation };
export const installation = (env: NodeJS.ProcessEnv = process.env) => resolveInstallation(config, env);
export const requireInstallation = (env: NodeJS.ProcessEnv = process.env, report?: (message: string) => never, requested?: string) => requireResolvedInstallation(config, env, report, requested);
export const namesInstallation = (value: Installation, want: string) => namesResolvedInstallation(config, value, want);
export const installationLine = (value: Installation, identity?: { stored: string | null; clear: boolean }) => formatInstallationLine(value, runningLine, identity);
export const installationRef = (value: Installation, identity?: { stored: string | null; clear: boolean }) => installationFields(value, runningRef, identity);
function selectedRelease(product: 'helmo', env: NodeJS.ProcessEnv): string | null { const named = env['INSTALLATION_RELEASE']?.trim(); if (!named) return null; const selectionFile = resolve(named); try { const selection = JSON.parse(readFileSync(selectionFile, 'utf8')) as { release?: string; directory?: string; components?: Record<string, { release?: string; commit?: string }> }; if (!selection.release || !selection.directory) throw new Error('selection lacks release or directory'); const releaseDir = resolve(dirname(selectionFile), selection.directory); const manifest = JSON.parse(readFileSync(join(releaseDir, 'RELEASE.json'), 'utf8')) as { commits?: Record<string, string> }; for (const repo of ['rev', 'helmo', 'helmo-roadmap']) { const component = selection.components?.[repo]; if (!component || component.release !== selection.release || component.commit !== manifest.commits?.[repo]) throw new Error(`${repo} does not match selected release ${selection.release}`); } const runningRoot = dirname(dirname(fileURLToPath(import.meta.url))); if (realpathSync(runningRoot) !== realpathSync(resolve(releaseDir, product))) throw new Error(`${product} is running from ${runningRoot}, not ${join(releaseDir, product)}`); return selection.release; } catch (error) { throw new InstallationError(`incoherent release set: ${product}: ${error instanceof Error ? error.message : String(error)}`); } }
