/* What this can prove without a network: that every file the official shadcn
   CLI generated is still exactly as it generated it, and that nothing
   unpinned has appeared beside it. Proving the manifest itself is upstream's
   output needs the registry, and that is `npm run upstream:check`. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pin = JSON.parse(readFileSync(join(root, 'upstream.json'), 'utf8'));
const sha = (path) => createHash('sha256').update(readFileSync(join(root, path))).digest('hex');

test('every generated file is byte-identical to what the pinned CLI wrote', () => {
  const entries = Object.entries(pin.files.manifest);
  assert.ok(entries.length >= 20, `expected the full generated set, got ${entries.length}`);
  const changed = entries.filter(([path, digest]) => sha(path) !== digest).map(([path]) => path);
  assert.deepEqual(changed, [], `edited generated source: ${changed.join(', ')} — ${pin.commands.refresh}`);
});

test('no component, hook or lib file sits outside the pin', () => {
  const found = [];
  for (const dir of [...pin.files.directories, 'src/lib']) {
    for (const entry of readdirSync(join(root, dir))) {
      if (statSync(join(root, dir, entry)).isFile()) found.push(`${dir}/${entry}`);
    }
  }
  const unpinned = found.filter((path) => !(path in pin.files.manifest));
  assert.deepEqual(unpinned, [], `not generated by the pinned CLI: ${unpinned.join(', ')}`);
});

test('the pin names the version, preset and inventory a refresh needs', () => {
  assert.match(pin.cli, /^\d+\.\d+\.\d+$/);
  assert.equal(pin.style, `${pin.base}-${pin.preset}`);
  assert.ok(pin.components.length > 0);
  for (const key of ['install', 'add', 'check', 'refresh', 'upgrade']) {
    assert.ok(pin.commands[key], `upstream.json records no ${key} command`);
  }
});

test('the application code is the only hand-written source', () => {
  assert.ok(pin.files.local.includes('src/App.tsx'));
  const app = readFileSync(join(root, 'src/App.tsx'), 'utf8');
  const imports = [...app.matchAll(/from "@\/components\/ui\/([a-z-]+)"/g)].map((match) => match[1]);
  assert.ok(imports.length > 0, 'the application imports no components');
  const missing = imports.filter((name) => !(`src/components/ui/${name}.tsx` in pin.files.manifest));
  assert.deepEqual(missing, [], `imported but not generated: ${missing.join(', ')}`);
});
