/* What this can prove without a network: that every file the official shadcn
   CLI generated is still exactly as it generated it, and that nothing
   unpinned has appeared beside it. Proving the manifest itself is upstream's
   output needs the registry, and that is `npm run upstream:check`. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pin = JSON.parse(readFileSync(join(root, 'upstream.json'), 'utf8'));
const sha = (path) => createHash('sha256').update(readFileSync(join(root, path))).digest('hex');

test('every generated file is byte-identical to what the pinned CLI wrote', () => {
  const entries = Object.entries(pin.files.manifest);
  assert.ok(entries.length >= 20, `expected the full generated set, got ${entries.length}`);
  const changed = entries.filter(([path, digest]) => sha(path) !== digest).map(([path]) => path);
  assert.deepEqual(changed, [], `edited generated source: ${changed.join(', ')} — ${pin.commands.refresh}`);
});

test('no component, hook or lib file sits outside the pin', () => {
  const found = [];
  for (const dir of [...pin.files.directories, 'src/lib']) {
    for (const entry of readdirSync(join(root, dir))) {
      if (statSync(join(root, dir, entry)).isFile()) found.push(`${dir}/${entry}`);
    }
  }
  const unpinned = found.filter((path) => !(path in pin.files.manifest));
  assert.deepEqual(unpinned, [], `not generated by the pinned CLI: ${unpinned.join(', ')}`);
});

/* Arthur's own selection, not derived from the pin. Everything else here
   reads upstream.json, so a pin edited to a different preset and refreshed
   would be internally consistent and pass; this is the one place that says
   WHICH configuration was asked for. Only he changes these lines. See UI.md. */
const requested = {
  preset: 'b6YWkyPAm',
  base: 'radix',
  font: 'inter',
  fontFamily: "'Inter Variable', sans-serif",
  fontPackage: '@fontsource-variable/inter',
  baseColor: 'mauve',
  radius: '0.45rem',
  iconLibrary: 'lucide',
};

test('the pin names the version, preset and inventory a refresh needs', () => {
  assert.match(pin.cli, /^\d+\.\d+\.\d+$/);
  assert.equal(pin.preset, requested.preset);
  assert.equal(pin.base, requested.base);
  assert.equal(pin.style, `${pin.base}-${pin.resolved.values.style}`);
  assert.equal(pin.resolved.values.baseColor, requested.baseColor);
  assert.equal(pin.resolved.values.font, requested.font);
  assert.deepEqual(pin.resolved.fallbacks, []);
  assert.ok(pin.components.length > 0);
  for (const key of ['install', 'add', 'check', 'refresh', 'upgrade']) {
    assert.ok(pin.commands[key], `upstream.json records no ${key} command`);
  }
  assert.ok(pin.commands.install.includes(`--preset ${requested.preset}`), 'the install command installs a different preset');
});

test('the generated configuration is the one that was asked for', () => {
  const components = JSON.parse(readFileSync(join(root, 'components.json'), 'utf8'));
  assert.equal(components.tailwind.baseColor, requested.baseColor);
  assert.equal(components.style, pin.style);
  assert.equal(components.iconLibrary, requested.iconLibrary);
  const css = readFileSync(join(root, 'src/index.css'), 'utf8');
  assert.ok(css.includes(`@import "${requested.fontPackage}";`), 'the generated CSS imports another font');
  assert.ok(css.includes(`--font-sans: ${requested.fontFamily};`), 'the generated CSS names another font family');
  assert.match(css, /html \{\n\s+@apply font-sans;/, 'nothing applies the font, so the chrome falls back to Times');
  assert.ok(css.includes(`--radius: ${requested.radius};`), 'the generated CSS carries another radius');
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  assert.ok(pkg.dependencies[requested.fontPackage], `package.json does not install ${requested.fontPackage}`);
});

test('the application code is the only hand-written source', () => {
  assert.ok(pin.files.local.includes('src/App.tsx'));
  /* Every hand-written module, not only App.tsx: a view that reached for a
     component nobody installed would build here and 404 after a refresh. */
  const sources = pin.files.local.filter((path) => path.endsWith('.tsx'));
  assert.ok(sources.length > 1, 'the pin records no view modules');
  const missing = [];
  for (const path of sources) {
    const source = readFileSync(join(root, path), 'utf8');
    const imports = [...source.matchAll(/from "@\/components\/ui\/([a-z-]+)"/g)].map((match) => match[1]);
    assert.ok(imports.length > 0, `${path} imports no components`);
    for (const name of imports) {
      if (!(`src/components/ui/${name}.tsx` in pin.files.manifest)) missing.push(`${path} → ${name}`);
    }
  }
  assert.deepEqual(missing, [], `imported but not generated: ${missing.join(', ')}`);
});
