// Machine-restart resilience: the supervisor as a user-level service.
// macOS: LaunchAgent with KeepAlive on unsuccessful exit only — launchd
// restarts a crashed supervisor, but a graceful drain (exit 0) stays down
// until the operator starts the machine again. Linux: systemd user unit,
// Restart=on-failure, same semantics. The unit embeds the install-time PATH
// and REV_HOME because service managers give daemons a bare environment and
// the agent CLIs the shim spawns must still resolve.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir, userInfo } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { explicitInstallationIdentity } from '@helmo/core';
import { DEFAULT_DRAIN_GRACE_SECONDS, revHome, stateDir } from './config.js';
import { processObservation } from './sentinels.js';
import { runCommand } from './command-name.js';

export const LAUNCHD_EXIT_TIMEOUT_SECONDS = 60;

/**
 * The entry point a PINNED installation's service definition names (H-2511).
 *
 * A definition is written once and nothing rewrites it, so whatever path it
 * carries is frozen at install time. Naming the running `cli.js` was therefore
 * naming a release directory: after `rev release upgrade` the job the service
 * manager brought back exec'd the release the installation had just left, was
 * stopped by rev's own coherence check (install.ts, `selectedRelease`), and
 * under KeepAlive was brought back to fail again. The upgrade's own output
 * promises the opposite — the installation "takes this release when it next
 * starts" — and it is the mechanism that should match the wording.
 *
 * So a pinned definition names this file instead. It lives in the
 * installation's own home, outside every release directory, and resolves the
 * selection at START rather than at install: a release change is picked up by
 * a restart, with no reinstall.
 *
 * An unpinned installation does not get one. It has no selection to resolve,
 * and the pre-H-2511 arrangement is already right for it, so its definition
 * still names the cli.js the install was run from.
 */
export function launcherPath(): string {
  return join(revHome(), 'service', 'launch.mjs');
}

// The one piece of code a release change cannot update: it is named by a frozen
// definition and rewritten only by `rev service install`. So it decides as
// little as possible — find the selected release's cli.js and hand over.
// VERIFYING the set stays in the product it loads, which now passes because the
// code came from the directory the selection names.
const LAUNCHER_SOURCE = `// GENERATED by \`rev service install\` (H-2511). Reinstalling rewrites it.
//
// The service definition that names this file is frozen at install time; this
// file is not, because it reads the release selection at every start. A release
// change is therefore picked up by a restart alone.
//
// Refusals exit non-zero on purpose. The service manager brings this back, and
// that is what makes a repaired selection self-healing: the next start resolves
// the fixed file and the supervisor returns without anyone running a command.
// Each attempt writes ONE line to the service log, never a stack trace.
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const who = process.env.HELMO_INSTALLATION?.trim() || process.env.REV_LABEL?.trim() || process.env.REV_HOME?.trim() || 'this installation';
const refuse = (why) => {
  console.error(\`rev: \${who} cannot start: \${why}\`);
  process.exit(1);
};

const named = process.env.INSTALLATION_RELEASE?.trim();
if (!named) {
  refuse('INSTALLATION_RELEASE is unset, so nothing says which release to load. Reinstall the service from the rev this installation should run: rev service install');
}
const file = resolve(named);
const bindingName = process.env.HELMO_BINDING?.trim();
let binding = null;
if (bindingName) {
  const bindingFile = resolve(bindingName);
  try { binding = JSON.parse(readFileSync(bindingFile, 'utf8')); }
  catch (e) { refuse(\`its installation binding \${bindingFile} is unreadable (\${e.message})\`); }
  if (!binding || binding.version !== 1 || !binding.installation || !binding.work?.home || !binding.work?.store
    || !binding.roadmap?.home || !binding.roadmap?.store || !binding.control?.home || !binding.control?.service) {
    refuse(\`its installation binding \${bindingFile} is incomplete or unsupported\`);
  }
  const pathBindings = { REV_HOME: binding.control.home, HELMO_HOME: binding.work.home, HELMO_DB: binding.work.store,
    ROADMAP_HOME: binding.roadmap.home, ROADMAP_DB: binding.roadmap.store };
  for (const [key, value] of Object.entries(pathBindings)) {
    if (process.env[key]?.trim() && resolve(process.env[key]) !== resolve(value)) refuse(\`\${key}=\${resolve(process.env[key])} conflicts with binding \${resolve(value)}\`);
    process.env[key] = resolve(value);
  }
  if (process.env.HELMO_INSTALLATION?.trim() && process.env.HELMO_INSTALLATION.trim() !== binding.installation) refuse(\`HELMO_INSTALLATION=\${process.env.HELMO_INSTALLATION} conflicts with binding \${binding.installation}\`);
  if (binding.control.service !== binding.installation) refuse(\`binding service \${binding.control.service} does not match installation \${binding.installation}\`);
  process.env.HELMO_INSTALLATION = binding.installation;
  process.env.HELMO_BINDING = bindingFile;
  process.env.HELMO_REQUIRE_BINDING = '1';
}
let selection;
try {
  selection = JSON.parse(readFileSync(file, 'utf8'));
} catch (e) {
  refuse(\`its release selection \${file} is unreadable (\${e.message}). Repair it with: rev release upgrade <release directory>\`);
}
if (!selection || typeof selection !== 'object' || Array.isArray(selection)
  || typeof selection.release !== 'string' || !selection.release.trim()
  || typeof selection.directory !== 'string' || !selection.directory.trim()) {
  refuse(\`its release selection \${file} names no release (it needs 'release' and 'directory'). Repair it with: rev release upgrade <release directory>\`);
}
if (binding && binding.release !== selection.release) refuse(\`release \${selection.release} conflicts with binding \${binding.release}\`);
const releaseDir = resolve(dirname(file), selection.directory);
let commits;
try {
  commits = JSON.parse(readFileSync(join(releaseDir, 'RELEASE.json'), 'utf8')).commits;
} catch (e) {
  refuse(\`release \${selection.release} has no readable RELEASE.json (\${e.message}). Select a release that does: rev release upgrade <release directory>\`);
}
const names = commits && typeof commits === 'object' ? Object.keys(commits).sort() : [];
const unified = names.length === 1 && names[0] === 'helmo';
const legacy = names.length === 3 && ['helmo', 'helmo-roadmap', 'rev'].every((name) => names.includes(name));
if (!unified && !legacy) {
  refuse(\`release \${selection.release} has an unsupported component set (\${names.join(', ') || 'none'}). Select a coherent release: rev release upgrade <release directory>\`);
}
const cli = unified
  ? join(releaseDir, 'helmo', 'packages', 'runtime', 'dist', 'cli.js')
  : join(releaseDir, 'rev', 'dist', 'cli.js');
if (!existsSync(cli)) {
  refuse(\`release \${selection.release} holds no rev to start at \${cli}. Select a release that does: rev release upgrade <release directory>\`);
}

// Hand over IN THIS PROCESS rather than spawning one: the service manager's
// signals, its exit timeout and the pid it supervises all have to reach the
// supervisor itself. argv[1] becomes the resolved cli.js so everything
// downstream — the loop drivers the supervisor spawns, REV_CLI in an agent's
// environment, the command line the sentinels record — is exactly what it would
// have been had the manager named that file directly.
process.env.REV_SERVICE_LAUNCHER = process.argv[1];
process.argv[1] = cli;
await import(pathToFileURL(cli).href);
`;

/** Write this installation's launcher, and answer with the path a definition
 *  should name. Idempotent: the content depends on nothing install-time. */
export function writeLauncher(): string {
  const launcher = launcherPath();
  mkdirSync(dirname(launcher), { recursive: true });
  writeFileSync(launcher, LAUNCHER_SOURCE);
  return launcher;
}

// The service identity follows the Rev home (H-2210). It used to be the
// constant 'dev.rev', and the label is also the plist filename and the
// bootout/kickstart address — so two fleets under one login fought over one
// job and one file, and the second install silently replaced the first.
//
// H-2452: deriving it from the home's BASENAME was still one identity for many
// installs. /tmp/customer-a/.rev and /tmp/customer-b/.rev are both '.rev', so
// both were 'dev.rev', and redirecting HOME does not separate them: a plist
// FILENAME lives under $HOME, but launchd's namespace is the uid's
// (`gui/<uid>/<label>`), so two installs under one account share one bootout
// and kickstart address whatever HOME says. The identity therefore has to be a
// function of the resolved home PATH.
//
// The conventional homes keep the label they are already bootstrapped under,
// by rule rather than by name: a direct child of the ACCOUNT's home directory
// called `.rev` or `.rev-<suffix>` cannot collide with another such home, so
// ~/.rev stays 'dev.rev' and ~/.rev-gp stays 'dev.rev.gp'. Anywhere else the
// label carries a digest of the resolved path, which is stable across restarts
// and distinct per install. A descriptive part comes first so the label is
// still readable: /tmp/customer-a/.rev -> 'dev.rev.customer-a.<digest>'.
//
// The account's home comes from the password database, not from $HOME, for the
// same reason the plist itself is a hazard here: a service manager hands a
// daemon an environment the software under test can have written, so an
// identity keyed on $HOME is keyed on something a second install can set
// (H-2210's own trap, one level up). $HOME still decides WHERE the definition
// file is written — that is `serviceFile()`, and it must stay that way.
//
// HELMO_INSTALLATION overrides the derivation outright, and `serviceInstall` writes it
// into the service environment so the running job resolves the same identity
// its operator installed.
export function serviceLabel(): string {
  const explicit = explicitInstallationIdentity(process.env);
  if (explicit) return explicit.label;
  const home = resolve(revHome());
  const suffix = labelSuffix(basename(home));
  if (isConventionalHome(home)) return suffix ? `dev.rev.${suffix}` : 'dev.rev';
  // A bare `.rev` says nothing; the directory holding it usually names the
  // install, so borrow that for the readable part before the digest.
  const descriptive = suffix || labelSuffix(basename(dirname(home)));
  return `dev.rev.${descriptive ? `${descriptive}.` : ''}${homeDigest(home)}`;
}

/** The label the pre-H-2452 rule produced for this home — basename only. Used
 *  to find and retire a definition installed under the old identity, which is
 *  the migration path for a non-conventional home. */
export function legacyServiceLabel(): string {
  const suffix = labelSuffix(basename(resolve(revHome())));
  return suffix ? `dev.rev.${suffix}` : 'dev.rev';
}

function labelSuffix(name: string): string {
  return name
    .replace(/^\.?rev(?=[-_.]|$)/, '')
    .replace(/^[-_.]+/, '')
    .replace(/[^A-Za-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** ~/.rev and ~/.rev-<suffix>, where ~ is the account's own home: the homes the
 *  suffixed-home convention covers, whose basenames are unique by construction
 *  because they are siblings in one directory. */
function isConventionalHome(home: string): boolean {
  return dirname(home) === accountHome() && conventionalTail(basename(home)) !== null;
}

/**
 * What a conventionally NAMED Rev home carries after `.rev` — '' for `.rev`,
 * '-gp' for `.rev-gp` — or null when the name is not one of that family.
 *
 * The convention is a family, not one product: the same tail on the Helmo
 * family's own names (`.helmo-gp`, `.helmo-roadmap-gp`) is the same
 * installation, and a DIFFERENT tail is a different one. That is what lets a
 * removal name the directories it owns instead of trusting the directory they
 * all sit in (H-2544, `removalBounds`), so the rule lives here beside the
 * identity it already decides rather than being spelled twice.
 *
 * Unlike `isConventionalHome` this asks only about the basename. The label has
 * to know WHERE the home sits, because only siblings in one directory are
 * unique by construction; a boundary is safer for not knowing — `.rev-a` and
 * `.rev-b` beside each other are separate installations wherever they are.
 */
export function conventionalTail(name: string): string | null {
  const m = /^\.rev([-_.].*)?$/.exec(name);
  return m ? (m[1] ?? '') : null;
}

function accountHome(): string {
  try {
    return resolve(userInfo().homedir);
  } catch {
    // No password entry (some containers). $HOME is then all there is, and a
    // wrong answer here only means a home gets a digest it did not need.
    return resolve(homedir());
  }
}

// Eight hex characters of the resolved path. Long enough that two installs on
// one machine will not collide, short enough to read back off a label. The
// input is `resolve()`d and not `realpath`ed, so a home reached through a
// symlink is a second identity — HELMO_INSTALLATION is the override when that is not
// what you meant.
function homeDigest(home: string): string {
  return createHash('sha256').update(home).digest('hex').slice(0, 8);
}

// systemd unit names are not reverse-DNS, so the launchd label is the single
// source and this is its unit spelling: dev.rev -> rev, dev.rev.gp -> rev-gp.
export function systemdUnitName(): string {
  return unitNameFor(serviceLabel());
}

function unitNameFor(label: string): string {
  return label.replace(/^dev\./, '').replace(/\./g, '-');
}

const xml = (s: string) => s.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c] as string));

export function launchdPlist(
  node: string,
  cli: string,
  opts: { label: string; home: string; path: string; logPath: string; release?: string; binding?: string },
): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${xml(opts.label)}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(node)}</string>
    <string>${xml(cli)}</string>
    <string>run</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>${xml(opts.path)}</string>
    <key>REV_HOME</key><string>${xml(opts.home)}</string>
    <!-- The label the operator installed under, not just the one launchd
         boots. Without it a service manager's bare environment re-derives the
         identity from the home, and an install whose label was explicit — or
         whose home moved — would run under one name and address another
         (H-2452). Every command run from inside the service now resolves the
         same label the job holds. -->
    <key>HELMO_INSTALLATION</key><string>${xml(opts.label)}</string>
    ${opts.release ? `<key>INSTALLATION_RELEASE</key><string>${xml(opts.release)}</string>` : ''}
    ${opts.binding ? `<key>HELMO_BINDING</key><string>${xml(opts.binding)}</string>\n    <key>HELMO_REQUIRE_BINDING</key><string>1</string>` : ''}
  </dict>
  <key>StandardOutPath</key><string>${xml(opts.logPath)}</string>
  <key>StandardErrorPath</key><string>${xml(opts.logPath)}</string>
  <!-- launchd clamps ExitTimeOut at 60 seconds (H-877). This buys the largest
       available window for loop drivers to finish; detached agent sessions
       remain the protection when a bootout becomes a hard stop. Use rev stop
       for a graceful drain that may outlast this service-manager ceiling. -->
  <key>ExitTimeOut</key><integer>${LAUNCHD_EXIT_TIMEOUT_SECONDS}</integer>
</dict>
</plist>
`;
}

export function systemdUnit(node: string, cli: string, opts: { home: string; path: string; label: string; release?: string; binding?: string }): string {
  return `[Unit]
Description=Rev — keeps agent loops turning

[Service]
ExecStart=${node} ${cli} run
Restart=on-failure
RestartSec=10
# Stop the supervisor, not the whole cgroup (H-467). Under the default
# KillMode=control-group systemd SIGTERMs every process in the unit, including
# the agent session mid-turn; the supervisor's own drain is what should end a
# loop, and it needs longer than the 90s default to do it.
KillMode=mixed
TimeoutStopSec=${DEFAULT_DRAIN_GRACE_SECONDS + 60}
Environment=PATH=${opts.path}
Environment=REV_HOME=${opts.home}
# The installed identity, for the reason the plist carries it (H-2452).
Environment=HELMO_INSTALLATION=${opts.label}
${opts.release ? `Environment=INSTALLATION_RELEASE=${opts.release}` : ''}
${opts.binding ? `Environment=HELMO_BINDING=${opts.binding}\nEnvironment=HELMO_REQUIRE_BINDING=1` : ''}

[Install]
WantedBy=default.target
`;
}

export function serviceFile(): { kind: 'launchd' | 'systemd'; file: string } {
  const kind = process.platform === 'darwin' ? 'launchd' : 'systemd';
  return { kind, file: serviceFilePath(kind, serviceLabel()) };
}

// Where a definition for a GIVEN label lives. Taking the label as an argument
// is what lets the migration look for the one this install used to have
// (H-2452); `homedir()` rather than the account home on purpose — $HOME decides
// where files go, the account decides who the service identity belongs to.
function serviceFilePath(kind: 'launchd' | 'systemd', label: string): string {
  return kind === 'launchd'
    ? join(homedir(), 'Library', 'LaunchAgents', `${label}.plist`)
    : join(homedir(), '.config', 'systemd', 'user', `${unitNameFor(label)}.service`);
}

function launchctl(...args: string[]): void {
  execFileSync('launchctl', args, { stdio: 'inherit' });
}

function inspectLaunchctl(...args: string[]): void {
  execFileSync('launchctl', args, { stdio: 'ignore' });
}

const pause = (ms: number): void => { Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms); };

/** launchctl bootout may return while a draining job still owns its label. */
export function waitForLaunchdExit(
  target: string,
  inspect: (...args: string[]) => void = inspectLaunchctl,
  timeoutMs = (LAUNCHD_EXIT_TIMEOUT_SECONDS + 5) * 1000,
  now: () => number = Date.now,
  wait: (ms: number) => void = pause,
): void {
  const deadline = now() + timeoutMs;
  while (now() < deadline) {
    try {
      inspect('print', target);
    } catch {
      return;
    }
    wait(50);
  }
  throw new Error(`timed out after ${timeoutMs}ms waiting for ${target} to stop`);
}

function systemctl(...args: string[]): void {
  execFileSync('systemctl', ['--user', ...args], { stdio: 'inherit' });
}

export function installLaunchd(
  file: string,
  plist: string,
  domain: string,
  label: string,
  run = launchctl,
  awaitExit: (target: string) => void = waitForLaunchdExit,
): void {
  const previous = existsSync(file) ? readFileSync(file, 'utf8') : null;
  writeFileSync(file, plist);
  const target = `${domain}/${label}`;
  let wasLoaded = true;
  try {
    run('bootout', target);
  } catch {
    wasLoaded = false;
    /* not loaded is fine */
  }
  if (wasLoaded) awaitExit(target);
  try {
    run('bootstrap', domain, file);
  } catch (error) {
    // Restore the definition as well as the running job. A failed bootstrap
    // after the new plist was written must not turn a reinstall into a silent
    // permanent outage.
    try { run('bootout', target); } catch { /* candidate never loaded */ }
    try { awaitExit(target); } catch { /* original error remains primary */ }
    if (previous === null) rmSync(file, { force: true });
    else writeFileSync(file, previous);
    if (previous !== null && wasLoaded) run('bootstrap', domain, file);
    throw error;
  }
}

/**
 * The Rev home a service definition already on disk says it is for, read out of
 * the definition itself (H-2452). This is what makes "is this service mine"
 * answerable before a write, a bootout or a kickstart: the label alone cannot
 * say, because an explicit REV_LABEL can be set to any string by any install.
 * `null` means the file holds no REV_HOME — an old definition, or not ours.
 */
export function definedHome(kind: 'launchd' | 'systemd', text: string): string | null {
  const m = kind === 'launchd'
    ? /<key>REV_HOME<\/key>\s*<string>([^<]*)<\/string>/.exec(text)
    : /^Environment=REV_HOME=(.*)$/m.exec(text);
  const found = m?.[1]?.trim();
  return found ? found.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>') : null;
}

/**
 * The program a definition on disk names — the file the service manager would
 * hand to node. The counterpart of `definedHome`, and read for the same reason:
 * what a definition says about itself is the only account of what a restart
 * would actually bring back (H-2511).
 */
export function definedProgram(kind: 'launchd' | 'systemd', text: string): string | null {
  const m = kind === 'launchd'
    ? /<key>ProgramArguments<\/key>\s*<array>\s*<string>[^<]*<\/string>\s*<string>([^<]*)<\/string>/.exec(text)
    : /^ExecStart=\S+ (\S+)/m.exec(text);
  const found = m?.[1]?.trim();
  return found ? found.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>') : null;
}

/**
 * A definition installed before H-2511 for an installation that is now pinned:
 * it names a cli.js frozen inside one release, so a release change leaves it
 * naming code the installation has left and the restart the change promises
 * cannot happen. One `rev service install` replaces it; until then a release
 * command says so rather than leaving the operator to find out from a
 * supervisor that will not come back.
 */
export function stalePinnedService(): { file: string; program: string } | null {
  if (!process.env['INSTALLATION_RELEASE']?.trim()) return null;
  const { kind, file } = serviceFile();
  if (!existsSync(file)) return null;
  const text = readFileSync(file, 'utf8');
  const owner = definedHome(kind, text);
  if (owner !== null && resolve(owner) !== resolve(revHome())) return null;
  const program = definedProgram(kind, text);
  if (!program || resolve(program) === launcherPath()) return null;
  return { file, program };
}

/**
 * Refuse to touch a definition that belongs to a different installation.
 *
 * With the identity bound to the resolved home this should not happen by
 * derivation any more, but an explicit REV_LABEL still lets two installs name
 * themselves the same thing — and the failure mode is silent: install, and the
 * other fleet's supervisor is booted out and replaced by yours. So the
 * destructive paths check the file's own REV_HOME first and stop, naming both
 * homes and the way out. A definition with no REV_HOME predates this and is
 * treated as ours, which is what keeps an existing install upgradeable.
 */
function assertOwnService(kind: 'launchd' | 'systemd', file: string, action: string): void {
  if (!existsSync(file)) return;
  const owner = definedHome(kind, readFileSync(file, 'utf8'));
  if (owner === null) return;
  const mine = resolve(revHome());
  if (resolve(owner) === mine) return;
  throw new Error(
    `refusing to ${action} ${file}: it is installation ${owner}'s service, not ${mine}'s.\n`
    + `Both installations resolve the service identity '${serviceLabel()}', so one of them must be given its own: `
    + `set REV_LABEL to a distinct name for this installation and run the command again.`,
  );
}

export function serviceInstall(): void {
  const { kind, file } = serviceFile();
  const node = process.execPath;
  const home = revHome();
  const path = process.env['PATH'] ?? '/usr/local/bin:/usr/bin:/bin';
  const release = process.env['INSTALLATION_RELEASE']?.trim();
  const binding = process.env['HELMO_BINDING']?.trim() ? resolve(process.env['HELMO_BINDING']!) : undefined;
  assertOwnService(kind, file, 'install over');
  // A pinned installation's definition names its own launcher, never the
  // cli.js this command happens to be running from — that one is inside a
  // release directory, and a definition outlives the release it was made in
  // (H-2511). Unpinned, there is no selection to resolve and nothing changes.
  const cli = release ? writeLauncher() : process.argv[1]!;
  mkdirSync(join(file, '..'), { recursive: true });
  const label = serviceLabel();
  if (kind === 'launchd') {
    const logPath = join(stateDir('supervisor'), 'launchd.log');
    const domain = `gui/${process.getuid!()}`;
    installLaunchd(file, launchdPlist(node, cli, { label, home, path, logPath, release, binding }), domain, label);
    console.log(`Installed and started: ${file}\nAny running supervisor was stopped and restarted; launchd allows its loop drivers 60 seconds to exit, while detached agent sessions continue to completion.\nThe supervisor now survives reboots. Logs: ${logPath}`);
  } else {
    const unit = systemdUnitName();
    writeFileSync(file, systemdUnit(node, cli, { home, path, label, release, binding }));
    systemctl('daemon-reload');
    systemctl('enable', '--now', unit);
    console.log(`Installed and started: ${file} (systemd user unit '${unit}').`);
  }
  retireLegacyService(kind, file);
  console.log(`Stop the machine gracefully with: ${runCommand} stop  (a drained supervisor stays down until started again)`);
}

export function serviceUninstall(): void {
  const { kind, file } = serviceFile();
  if (!existsSync(file)) {
    console.log(`No service installed (${file} not found).`);
    return;
  }
  assertOwnService(kind, file, 'uninstall');
  if (kind === 'launchd') {
    try {
      launchctl('bootout', `gui/${process.getuid!()}/${serviceLabel()}`);
    } catch {
      /* not loaded is fine — still remove the file */
    }
  } else {
    try {
      systemctl('disable', '--now', systemdUnitName());
    } catch {
      /* not enabled is fine */
    }
  }
  rmSync(file);
  console.log(`Uninstalled: ${file}`);
}

export function serviceStart(): void {
  const { kind, file } = serviceFile();
  assertOwnService(kind, file, 'start');
  if (kind === 'launchd') launchctl('kickstart', `gui/${process.getuid!()}/${serviceLabel()}`);
  else systemctl('start', systemdUnitName());
  console.log(`Supervisor start requested — check: ${runCommand} status`);
}

/**
 * The migration path for a non-conventional home (H-2452). Such a home's label
 * used to be its basename alone and now carries a path digest, so a service
 * installed before this change sits at the old path under the old name, still
 * loaded, still running that install's supervisor. Reinstalling would otherwise
 * leave two definitions for one installation and two jobs racing one queue.
 *
 * Only a definition that names THIS home is touched — it is unambiguously this
 * installation's own, which is what makes removing it safe rather than a guess.
 */
export function retireLegacyService(
  kind: 'launchd' | 'systemd',
  current: string,
  { launch = launchctl, system = systemctl }: { launch?: typeof launchctl; system?: typeof systemctl } = {},
): string | null {
  const legacy = serviceFilePath(kind, legacyServiceLabel());
  if (legacy === current || !existsSync(legacy)) return null;
  const owner = definedHome(kind, readFileSync(legacy, 'utf8'));
  if (owner === null || resolve(owner) !== resolve(revHome())) return null;
  if (kind === 'launchd') {
    try {
      launch('bootout', `gui/${process.getuid!()}/${legacyServiceLabel()}`);
    } catch {
      /* not loaded is fine — the file still has to go */
    }
  } else {
    try {
      system('disable', '--now', unitNameFor(legacyServiceLabel()));
    } catch {
      /* not enabled is fine */
    }
  }
  rmSync(legacy);
  console.log(`Retired this installation's previous service definition ${legacy}: its identity is now ${serviceLabel()}.`);
  return legacy;
}

export function serviceStatusLine(): string {
  const { file } = serviceFile();
  const supervisor = processObservation('supervisor');
  return `service file: ${existsSync(file) ? file : `not installed (${file})`}\nsupervisor:   ${supervisor.state === 'unknown' ? `unobservable (recorded pid ${supervisor.pid})` : supervisor.pid ? `running (pid ${supervisor.pid})` : 'down'}`;
}
